before_script:
  - npm install -g elm
script: 
  - elm package install --yes
  - elm-make Main.elm --output=index.html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master