before_script:
  - npm install elm
script: 
  - node_modules/.bin/elm-package install --yes
  - node_modules/.bin/elm-make Main.elm --output=index.html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master